owner: bhdicaire 
repo: status-page
user-agent: bhdicaire

assignees: bhdicaire

status-website:
  name: " " # dicaire.com status page
  cname: status.bhdicaire.com
  introTitle: "**Status page**"
  introMessage: "**Cloud providers:** [Apple](https://www.apple.com/support/systemstatus/), [AWS](https://health.aws.amazon.com/health/status), [Azure]( https://azure.status.microsoft/en-ca/status
), [Google Cloud](https://status.cloud.google.com/regional/americas), [Google Workspace](https://www.google.com/appsstatus/dashboard/), [MS](https://status.cloud.microsoft/), [MS 365](https://portal.office.com/adminportal/home?#/servicehealth), and [OVH](https://public-cloud.status-ovhcloud.com/)"
  logoUrl: https://raw.githubusercontent.com/bhdicaire/status-page/main/assets/dicaire-logo.svg
  logoHref: https://BHDicaire.com
  faviconSvg: https://raw.githubusercontent.com/dicaire/status-page/main/assets/dicaire-icon.svg
  favicon: https://raw.githubusercontent.com/dicaire/status-page/main/assets/dicaire-icon.png
  navbar:
    - title: Status
      href: /
    - title: Cloudflare
      href: https://www.cloudflarestatus.com/
    - title: GitHub
      href: https://www.githubstatus.com/
    - title: Zoom
      href: https://status.zoom.us/
  customBodyHtml: "<script src='https://cdn.usefathom.com/script.js' data-site='BEWPUJUT' defer></script>"
  themeUrl: https://status.dicaire.com/dcom.css

sites:
  - name: 'www.BHDicaire.com'
    url: https://BHDicaire.com
    icon: https://Dicaire.com/favicon.png
  - name: 'DNS – syeef.ns.Cloudflare.com'
    check: "tcp-ping"
    url: syeef.ns.cloudflare.com
    port: 53
    icon: https://www.cloudflare.com/favicon.ico
  - name: 'DNS – eve.ns.cloudflare.com'
    check: "tcp-ping"
    url: eve.ns.cloudflare.com
    port: 53
    icon: https://www.cloudflare.com/favicon.ico

# notifications:
#   - type: slack
#     channel: 
    
i18n:
  footer: ""